name: Build
on:
  pull_request: {}
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      CI: 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Determine Ruby version
        id: ruby_version
        run: |
          echo "::set-output name=RUBY_VERSION::$(cat .ruby-version)"
      - name: Set up build cache (bundler)
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-bundler
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ steps.ruby_version.outputs.RUBY_VERSION }}
      - name: Set up RubyGems
        run: |
          echo "gem: --no-document" > ~/.gemrc
      - name: Set up Bundler
        run: |
          gem install bundler
          bundle config path "vendor/bundle"
          bundle config jobs "$(nproc)"
      - name: Install dependencies (bundler)
        run: bundle install
      - name: Run tests
        run: bundle exec rake test
